### PR TITLE
docs: update readme to use release v4.0.1

### PR DESCRIPTION
**Pull request by chlip2**
## Description

Related issue: [BL-16691](https://dvsa.atlassian.net/browse/BL-16691)

## Before submitting (or marking as "ready for review")

- [x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [x] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

### CODE REVIEW

**Review by ccurran01 — APPROVED** [review]

**Comment by chlip2** [comment]
@JoshuaLicense sorry for that, it's the last one. Now everything works and readme is up to date.

**Comment by JoshuaLicense** [comment]
When this is merged, the next tag is 4.0.2. Do we need to reference that version?

**Comment by chlip2** [comment]
All changes due to workflow and actions are in v4.0.1. Do we need a new version after every merge? If not we are fine with v4.0.1 in readme. If not let me know and will change version here

**Review by JoshuaLicense — APPROVED** [review]

**Comment by sdh100shaun** [comment]
thanks @chlip2

**Pull request merged**
